// ROTAS DAS CATEGORIAS

GET http://localhost:3000/categoria
###

GET http://localhost:3000/categoria/112
###

POST http://localhost:3000/categoria/cadastro
Content-Type: application/json 

{
    "condigoSlug": "condigoSlunaldjk123f96",
    "titulo": "bebidas",
    "status": 1
}

###

PUT http://localhost:3000/categoria/editar/251
Content-Type: application/json 

{
    "condigoSlug": "kdsjfkasljaksfs",
    "titulo": "limpeza",
    "status": 1
}

###

DELETE http://localhost:3000/categoria/193

// ....

// ROTAS DOS PROTUDOS
###

GET http://localhost:3000/produtos
###

GET http://localhost:3000/produtos/407

###
POST http://localhost:3000/produtos
Content-Type: application/json 

{
    "idCategoria": "193",
    "codigoSKU": "kasnkankjfakf",
    "nome": "arroz",
    "descricao": "melhor arroz do mundo",
    "valor": 21.50,
    "status": 0
}
###

PATCH http://localhost:3000/produtos/215
Content-Type: application/json 

{
    "codigoSKU": "kasnkankjfakf",
    "nome": "arroz leite",
    "descricao": "melhor arroz de leite do mundo",
    "valor": 22.50,
    "status": 1
} 

###

DELETE  http://localhost:3000/produtos/407